import { Col, Row, Space } from "antd"
import styles from "./Layout.module.scss"
import { LeftOutlined, RightOutlined } from "@ant-design/icons"
import { ILayoutSupportProps } from "type"
import { useRouter } from "next/router"
import { useState } from "react"
import { Header } from "./Header.own"

export const LayoutOrderManage = ({ children }: ILayoutSupportProps) => {
  const router = useRouter()

  const [sideOpen, setSideOpen] = useState(true)

  return (
    <Col className={styles.layout_mine_container}>
      <Header pageTitle="Order Manage" />
      <Row className={sideOpen ? styles.main_container : styles.main_container_side_close}>
        {sideOpen ? (
          <Col className={styles.side_menu_container}>
            <Row className={styles.side_menu_title} justify={"space-between"} align={"middle"}>
              <Col>ORDER MANAGE</Col>
              <Col>
                <LeftOutlined onClick={() => setSideOpen(state => !state)} className={styles.side_menu_icon} />
              </Col>
            </Row>
            <Space direction="vertical" size={0} className={styles.support_side_menu_list}>
              <Row
                onClick={() => {
                  void router.push(`/ordermanage`)
                }}
                className={styles.side_sub_menu_active}
              >
                History
              </Row>
            </Space>
          </Col>
        ) : (
          <Space className={styles.side_menu_container_side_close}>
            <RightOutlined onClick={() => setSideOpen(state => !state)} className={styles.side_menu_icon} />
          </Space>
        )}
        <Col>{children}</Col>
      </Row>
      {/*
      head title 기획 전달 후 개발
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
    </Col>
  )
}
